posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.PostList.as_view(), name='all'),
    path('new/', views.CreatePost.as_view(), name='create'),
    path('by/<slug:slug>', views.UserPosts.as_view(), name='for_user'),
    path('by/<slug:slug>/<int:pk>/', views.PostDetail.as_view(), name='single'),
    path('delete/<int:pk>/', views.DeletePost.as_view(), name='delete'),
    path('<int:pk>/like/', views.LikeView.as_view(), name='like'),
    path('<int:pk>/unlike/', views.UnlikeView.as_view(), name='unlike'),
    path('<slug:slug>/likes', views.UserLikesPostsList.as_view(), name='user_likes'),
]

social/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import views
from posts import views as post_view

urlpatterns = [
    path('', post_view.PostList.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls'), name='accounts'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('posts/', include('posts.urls'), name='posts'),
    path('<slug:slug>/', include('user_profile.urls'), name='profile'),
    path('update_server/', views.update, name='update'),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls))
    ] + urlpatterns

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

user_profile/urls.py
from django.urls import path

from . import views
from posts.views import UserPosts

app_name = 'user_profile'

urlpatterns = [
    # path('find', views.PostList.as_view(), name='find'),
    # path('bla/', views.ShowProfile.as_view(), name='profile'),
    path('', views.ProfileDetail.as_view(), name='profile_detail'),
    path('posts/', UserPosts.as_view(), name='myposts'),
    path('update-profile/', views.UserProfileUpdateView.as_view(), name='edit_profile'),
    path('people', views.ProfileListAll.as_view(), name='people'),
    path('following', views.ProfileListFollowing.as_view(), name='following'),
    path('followers', views.ProfileListFollowers.as_view(), name='followers'),
    path('follow', views.FollowView.as_view(), name='follow'),
    path('unfollow', views.UnfollowView.as_view(), name='unfollow'),
]

user_profile/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
from posts.models import Post
from PIL import Image

class UserProfile(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    website = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='user_profile/pics', default='user_profile/default_profile_pic.png')
    bio = models.CharField(max_length=200, blank=True, default='')
    slug = models.SlugField(default="", null=False)
    followers = models.ManyToManyField(User, blank=True, related_name='followers')
    following = models.ManyToManyField(User, blank=True, related_name='following')
    likes = models.ManyToManyField(Post, blank=True, related_name='post_likes')

    def __str__(self):
        return f'{self.user.username} Profile'
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.user.username)
        super().save( *args, **kwargs)

        img = Image.open(self.profile_pic.path) # Open image

        # resize image
        if img.height > 80 or img.width > 80:
            output_size = (80, 80)
            img.thumbnail(output_size) # Resize image
            img.save(self.profile_pic.path) # Save it again and override the larger image

    def follow(self, other_user):
        if other_user.user not in self.following.all() and self.user not in other_user.followers.all():
            self.following.add(other_user.user)
            other_user.followers.add(self.user)

    def unfollow(self, other_user):
        if other_user.user in self.following.all() and self.user in other_user.followers.all():
            self.following.remove(other_user.user)
            other_user.followers.remove(self.user)

    @property
    def followers_count(self):
        return self.followers.count()

    @property
    def following_count(self):
        return self.following.count()
    
    @property
    def likes_count(self):
        return self.likes.count()
    

user_profile/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfile

class UserProfileForm(forms.ModelForm):
    class Meta():
        model = UserProfile
        fields = ('website','profile_pic', 'bio')

class UserProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['website','profile_pic', 'bio']

user_profile/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404, HttpResponseRedirect
from django.urls import reverse_lazy, reverse
from django.views import generic
from .forms import UserProfileUpdateForm
from . import models
from accounts.forms import UserUpdateForm

user_model = get_user_model()

class UserProfileUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = models.UserProfile
    form_class = UserProfileUpdateForm
    second_form_class = UserUpdateForm
    template_name = 'user_profile/edit_profile.html'

    def get_object(self):
        active_user_profile = models.UserProfile.objects.get(user=self.request.user)
        return active_user_profile

    def get_context_data(self, **kwargs):
        context = super(UserProfileUpdateView, self).get_context_data(**kwargs)
        if 'user_form' not in context:
            context['user_form'] = self.second_form_class(instance=self.request.user)
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.form_class(request.POST,
                               request.FILES,
                               instance=request.user.userprofile)
        user_form = self.second_form_class(request.POST, instance=request.user)

        if form.is_valid() and user_form.is_valid():
            form.save()
            user_form.save()
            messages.success(self.request, 'Profile updated successfully')
            return HttpResponseRedirect(self.get_success_url())
        else:
            return self.render_to_response(
              self.get_context_data(form=form, user_form=user_form))

    def get_success_url(self):
        slug = self.get_object().slug
        return reverse_lazy('user_profile:profile_detail', kwargs={'slug': slug})


class ProfileListAll(LoginRequiredMixin, generic.ListView):
    template_name = 'user_profile/profile_list_all.html'
    model = models.UserProfile


class ProfileListFollowing(LoginRequiredMixin, generic.ListView):
    template_name = 'user_profile/profile_list_following.html'
    model = models.UserProfile

    def get_queryset(self, *args, **kwargs): 
        following = models.UserProfile.objects.get(slug__iexact=self.kwargs.get('slug')).following.all()
        queryset = super(ProfileListFollowing, self).get_queryset(*args, **kwargs)
        queryset = queryset.filter(user__in=following)
        return queryset
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['profile_details'] = models.UserProfile.objects.get(slug__iexact=self.kwargs.get('slug'))
        return context


class ProfileListFollowers(LoginRequiredMixin, generic.ListView):
    template_name = 'user_profile/profile_list_followers.html'
    model = models.UserProfile

    def get_queryset(self, *args, **kwargs): 
        followers = models.UserProfile.objects.get(slug__iexact=self.kwargs.get('slug')).followers.all()
        queryset = super(ProfileListFollowers, self).get_queryset(*args, **kwargs)
        queryset = queryset.filter(user__in=followers)
        return queryset
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['profile_details'] = models.UserProfile.objects.get(slug__iexact=self.kwargs.get('slug'))
        return context


class ProfileDetail(LoginRequiredMixin, generic.DetailView):
    model = models.UserProfile

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user_details'] = user_model.objects.get(username__iexact=self.kwargs.get('slug'))
        profile_details = models.UserProfile.objects.get(slug__iexact=self.kwargs.get('slug'))
        is_following = self.request.user in profile_details.followers.all()
        context['is_following'] = is_following
        return context


class FollowView(LoginRequiredMixin, generic.RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        return reverse("user_profile:profile_detail", kwargs={'slug': self.kwargs.get('slug')})

    def get(self, request, *args, **kwargs):
        try:
            following_user_profile = models.UserProfile.objects.filter(
                user=self.request.user,
            ).get()
            followed_user_profile = models.UserProfile.objects.filter(
                slug=self.kwargs.get("slug")
            ).get()

        except models.UserProfile.DoesNotExist:
            messages.warning(
                self.request,
                "Something went wrong..."
            )

        else:
            following_user_profile.follow(followed_user_profile)
            messages.success(
                self.request,
                "You started to follow " + followed_user_profile.slug + "."
            )
        return super().get(request, *args, **kwargs)


class UnfollowView(LoginRequiredMixin, generic.RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        return reverse("user_profile:profile_detail", kwargs={'slug': self.kwargs.get('slug')})

    def get(self, request, *args, **kwargs):
        try:
            following_user_profile = models.UserProfile.objects.filter(
                user=self.request.user,
            ).get()
            followed_user_profile = models.UserProfile.objects.filter(
                slug=self.kwargs.get("slug")
            ).get()

        except models.UserProfile.DoesNotExist:
            messages.warning(
                self.request,
                "Something went wrong..."
            )

        else:
            following_user_profile.unfollow(followed_user_profile)
            messages.success(
                self.request,
                "You stopped following " + followed_user_profile.slug + "."
            )
        return super().get(request, *args, **kwargs)

user_profile/templates/user_profile/_profile_card.html
<div class="d-sm-inline-flex flex-sm-wrap">
  {% for userprofile in userprofile_list %}
    <div class="card text-center shadow-sm overflow-hidden m-4" style="width: 12rem;">
        <div class="card-body">
          <a href="{% url 'user_profile:profile_detail' slug=userprofile.slug %}" class="text-decoration-none">
            <h5 class="card-title">
                <img class="rounded-circle profile-pic" src="{{ userprofile.profile_pic.url }}"
                    alt="Pofile picture of {{ userprofile.slug }}"/>
            </h5>
            <p class="card-text"><strong>{{ userprofile.slug }}</strong></p>
          </a>
          <h6 class="card-subtitle mb-2 text-muted mt-3">
            <a href="{% url 'user_profile:following' slug=userprofile.slug %}" class="text-decoration-none">
              Following {{ userprofile.following_count }}
            </a>
          </h6>
          <h6 class="card-subtitle mb-2 text-muted">
            <a href="{% url 'user_profile:followers' slug=userprofile.slug %}" class="text-decoration-none">
              Followers {{ userprofile.followers_count }}
            </a>
          </h6>
          <h6 class="card-subtitle mb-2 text-muted">
            <a href="{% url 'posts:user_likes' slug=userprofile.slug %}" class="text-decoration-none">
              Likes {{ userprofile.likes_count }}
            </a>
          </h6>
        </div>
    </div>
  {% empty %}
    <p class="m-4">No one here yet.</p>
  {% endfor %}
</div>

user_profile/templates/user_profile/edit_profile.html
{% extends "base.html" %}
{% load bootstrap5 %}

{% block content %}
<div class="content-section">
  <div class="media">
    <img
      class="rounded-circle account-img"
      src="{{ user.userprofile.profile_pic.url }}"
      alt="Profile picture of {{ user.username }}"
    />
    <div class="media-body">
      <h2 class="account-heading">{{ user.username }}</h2>
    </div>
  </div>
  <!-- FORM HERE -->
  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Profile Info</legend>
      {% bootstrap_form user_form %}
      <!-- User form -->
      {% bootstrap_form form %}
      <!-- Profile form -->
    </fieldset>
    <div class="form-group">
      <button class="btn btn-primary" type="submit">
        <span class="material-symbols-outlined">
					save
				</span>
				<span class="icon-label">Save</span>
      </button>
    </div>
  </form>
</div>
{% endblock content %}

user_profile/templates/user_profile/profile_list_all.html
{% extends "base.html" %}

{% block content %}
  <h1 class="font-cursive">People</h1>
  <div class="row justify-content-center">
    <div class="col-md-8">
      {% include "user_profile/_profile_card.html" %}
    </div>
  </div>
{% endblock content %}

user_profile/templates/user_profile/profile_list_followers.html
{% extends "base.html" %}

{% block content %}
  <h1 class="font-cursive">The followers of {{ profile_details.slug }}</h1>
  <div class="row justify-content-center">
    <div class="col-md-8">
      {% include "user_profile/_profile_card.html" %}
    </div>
  </div>
{% endblock content %}

user_profile/templates/user_profile/profile_list_following.html
{% extends "base.html" %}

{% block content %}
  <h1 class="font-cursive">{{ profile_details.slug }} is following</h1>
  <div class="row justify-content-center">
    <div class="col-md-8">
      {% include "user_profile/_profile_card.html" %}
    </div>
  </div>
{% endblock content %}

user_profile/templates/user_profile/userprofile_detail.html
{% extends "base.html" %}

{% block content %}
<div class="content-section">
  <div class="media">
    <img
      class="rounded-circle profile-pic"
      src="{{ user_details.userprofile.profile_pic.url }}"
      alt="Pofile picture of {{ user_details.username }}"
    />
    <div class="media-body">
      <h2 class="account-heading">{{ user_details.username }}</h2>
      <p class="text-secondary">{{ user_details.email }}</p>
      <p>Website: <a href="{{ user.userprofile.website }}">{{ user_details.userprofile.website }}</a></p>
      <p>Bio: {{ user_details.userprofile.bio }}</p>
      <p><a href="{% url 'user_profile:following' slug=user_details.username %}">
        Following {{ user_details.userprofile.following_count }}
      </a></p>
      <p><a href="{% url 'user_profile:followers' slug=user_details.username %}">
        Followers {{ user_details.userprofile.followers_count }}
      </a></p>
      <div class="">
      {% if user.is_authenticated %}
        {% if user_details == user %}
          <a href="{% url 'user_profile:edit_profile' slug=user.username %}" title="delete" class="btn btn-outline-primary">
            Update
          </a>
        {% else %}
          {% if is_following %}
            <form method="POST" action="{% url 'user_profile:unfollow' slug=user_details.username %}">
              {% csrf_token %}
              <button class="btn btn-outline-warning" type=submit>Unfollow</button>
            </form>
          {% else %}
            <form method="POST" action="{% url 'user_profile:follow' slug=user_details.username %}">
              {% csrf_token %}
              <button class="btn btn-outline-primary" type=submit>Follow</button>
            </form>
          {% endif %}
        {% endif %}
			{% endif %}
		</div>
  </div>
</div>
{% endblock content %}