accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('activate/<uidb64>/<token>/', views.ActivateView.as_view(), name="activate"),
    path('check-email/', views.CheckEmailView.as_view(), name="check_email"),
    path('success/', views.SuccessView.as_view(), name="success"),
]

posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.PostList.as_view(), name='all'),
    path('new/', views.CreatePost.as_view(), name='create'),
    path('by/<slug:slug>', views.UserPosts.as_view(), name='for_user'),
    path('by/<slug:slug>/<int:pk>/', views.PostDetail.as_view(), name='single'),
    path('delete/<int:pk>/', views.DeletePost.as_view(), name='delete'),
    path('<int:pk>/like/', views.LikeView.as_view(), name='like'),
    path('<int:pk>/unlike/', views.UnlikeView.as_view(), name='unlike'),
    path('<slug:slug>/likes', views.UserLikesPostsList.as_view(), name='user_likes'),
]

social/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import views
from posts import views as post_view

urlpatterns = [
    path('', post_view.PostList.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls'), name='accounts'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('posts/', include('posts.urls'), name='posts'),
    path('<slug:slug>/', include('user_profile.urls'), name='profile'),
    path('update_server/', views.update, name='update'),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls))
    ] + urlpatterns

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/models.py
from django.contrib import auth

# Create your models here.
class User(auth.models.User, auth.models.PermissionsMixin):
    
    def __str__(self):
        return f'@{self.username}'
    

accounts/forms.py
from typing import Any
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.template.loader import render_to_string
from .token import token_generator

user_model = get_user_model()

class SignUpForm(UserCreationForm):

    email = forms.EmailField(
        max_length=254,
        help_text='Enter a valid email address'
    )

    class Meta:
        fields = ('username', 'email', 'password1', 'password2')
        model = user_model


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'Display Name'
        self.fields['email'].label = 'Email Address'

    def save(self, commit=True):
        user = super().save(commit=False)
        user.is_active = False
        if commit:
            user.save()
        return user
    
    def send_activation_email(self, request, user):
        current_site = get_current_site(request)
        subject = 'Activate Your Account'
        message = render_to_string(
            'accounts/activate_account.html',
            {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': token_generator.make_token(user),
            }
        )

        user.email_user(subject, message, html_message=message)


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = user_model
        fields = ['email']

accounts/views.py
from django.shortcuts import render
from django.views.generic import CreateView, TemplateView, RedirectView
from django.contrib.auth import login
from django.urls import reverse_lazy
from django.utils.http import urlsafe_base64_decode
from django.utils.encoding import force_str

from .forms import SignUpForm, token_generator, user_model

# Create your views here.
class SignUpView(CreateView):
    form_class = SignUpForm
    success_url = reverse_lazy('accounts:check_email')
    template_name = 'accounts/signup.html'

    def form_valid(self, form):
        to_return = super().form_valid(form)

        user = form.save()
        user.is_active = False # Turns the user status to inactive
        user.save()

        form.send_activation_email(self.request, user)

        return to_return


class ActivateView(RedirectView):

    url = reverse_lazy('accounts:success')

    # Custom get method
    def get(self, request, uidb64=None, token=None):

        try:
            uid = force_str(urlsafe_base64_decode(uidb64))
            user = user_model.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, user_model.DoesNotExist):
            user = None

        if user is not None and token_generator.check_token(user, token):
            user.is_active = True
            user.save()
            login(request, user)
            return super().get(request, uidb64, token)
        else:
            return render(request, 'accounts/activate_account_invalid.html')


class CheckEmailView(TemplateView):

    template_name = 'accounts/check_email.html'


class SuccessView(TemplateView):

    template_name = 'accounts/success.html'

accounts/templates/accounts/activate_account.html
<div>
    <h2>Hey {{ user.username }}</h2>

    <h3>We noticed you just sign up on our website<h3>
    <a href="http://{{ domain }}{% url 'accounts:activate' uidb64=uid token=token %}">Please <strong>confirm your email address</strong> and activate your account</a>
</div>

accounts/templates/accounts/activate_account_invalid.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <h1>Something went wrong</h1>
    </div>
{% endblock %}

accounts/templates/accounts/check_email.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <h1>Activate your account</h1>
        <p>Please check your inbox and verify your email address</p>
    </div>
{% endblock %}

accounts/templates/accounts/login.html
{% extends "base.html" %}
{% load bootstrap5 %}

{% block content %}
    <div class="container">
        <h1 class="font-cursive">Login</h1>
        <form method="POST">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
                <button type="submit" class="btn btn-primary">
                Login
                </button>
            {% endbuttons %}
        </form>
    </div>
{% endblock  %}

accounts/templates/accounts/signup.html
{% extends "base.html" %}
{% load bootstrap5 %}

{% block content %}
    <div class="container">
        <h1 class="font-cursive">Sign Up</h1>
        <form method="POST">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
                <button type="submit" class="btn btn-primary">
                Sign Up
                </button>
            {% endbuttons %}
        </form>
    </div>
{% endblock  %}

accounts/templates/accounts/success.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <h1>Your account has been verified.</h1>
    </div>
{% endblock %}