accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('activate/<uidb64>/<token>/', views.ActivateView.as_view(), name="activate"),
    path('check-email/', views.CheckEmailView.as_view(), name="check_email"),
    path('success/', views.SuccessView.as_view(), name="success"),
]

posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.PostList.as_view(), name='all'),
    path('new/', views.CreatePost.as_view(), name='create'),
    path('by/<slug:slug>', views.UserPosts.as_view(), name='for_user'),
    path('by/<slug:slug>/<int:pk>/', views.PostDetail.as_view(), name='single'),
    path('delete/<int:pk>/', views.DeletePost.as_view(), name='delete'),
    path('<int:pk>/like/', views.LikeView.as_view(), name='like'),
    path('<int:pk>/unlike/', views.UnlikeView.as_view(), name='unlike'),
    path('<slug:slug>/likes', views.UserLikesPostsList.as_view(), name='user_likes'),
]

social/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import views
from posts import views as post_view

urlpatterns = [
    path('', post_view.PostList.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls'), name='accounts'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('posts/', include('posts.urls'), name='posts'),
    path('<slug:slug>/', include('user_profile.urls'), name='profile'),
    path('update_server/', views.update, name='update'),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls))
    ] + urlpatterns

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

user_profile/urls.py
from django.urls import path

from . import views
from posts.views import UserPosts

app_name = 'user_profile'

urlpatterns = [
    # path('find', views.PostList.as_view(), name='find'),
    # path('bla/', views.ShowProfile.as_view(), name='profile'),
    path('', views.ProfileDetail.as_view(), name='profile_detail'),
    path('posts/', UserPosts.as_view(), name='myposts'),
    path('update-profile/', views.UserProfileUpdateView.as_view(), name='edit_profile'),
    path('people', views.ProfileListAll.as_view(), name='people'),
    path('following', views.ProfileListFollowing.as_view(), name='following'),
    path('followers', views.ProfileListFollowers.as_view(), name='followers'),
    path('follow', views.FollowView.as_view(), name='follow'),
    path('unfollow', views.UnfollowView.as_view(), name='unfollow'),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
{% load bootstrap5 %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MySocial</title>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Agbalumo&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <link href="https://cdn.jsdelivr.net/npm/bootswatch@5.3.2/dist/sandstone/bootstrap.min.css" rel="stylesheet">
    
    <link rel="stylesheet" href="{% static 'css/master.css' %}">
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark" role="navigation">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'home' %}">MySocial</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
               {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'posts:create' %}">New Post</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'user_profile:people' slug=user.username %}">People</a>
                    </li>
                {% endif %}
            </ul>
            <ul class="navbar-nav d-flex">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'user_profile:profile_detail' slug=user.username %}">{{ user.username }}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:signup' %}">Sign Up</a>
                    </li>
                {% endif %}
            </ul>
          </div>
        </div>
    </nav>
    <div class="container mt-4">
        {% block content %}
        {% endblock%}
    </div>
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block content %}
    <h1 class="font-cursive">Welcome to MySocial</h1>
{% endblock %}