posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.PostList.as_view(), name='all'),
    path('new/', views.CreatePost.as_view(), name='create'),
    path('by/<slug:slug>', views.UserPosts.as_view(), name='for_user'),
    path('by/<slug:slug>/<int:pk>/', views.PostDetail.as_view(), name='single'),
    path('delete/<int:pk>/', views.DeletePost.as_view(), name='delete'),
    path('<int:pk>/like/', views.LikeView.as_view(), name='like'),
    path('<int:pk>/unlike/', views.UnlikeView.as_view(), name='unlike'),
    path('<slug:slug>/likes', views.UserLikesPostsList.as_view(), name='user_likes'),
]

social/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import views
from posts import views as post_view

urlpatterns = [
    path('', post_view.PostList.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls'), name='accounts'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('posts/', include('posts.urls'), name='posts'),
    path('<slug:slug>/', include('user_profile.urls'), name='profile'),
    path('update_server/', views.update, name='update'),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls))
    ] + urlpatterns

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

posts/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth import get_user_model

import misaka

# Create your models here.
user_model = get_user_model()

class Post(models.Model):
    user = models.ForeignKey(user_model, related_name='posts', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now=True)
    post_pic = models.ImageField(upload_to='posts/images/')
    message = models.TextField(blank=True, default='')
    message_html = models.TextField(editable=False, blank=True, default='')
    likes = models.ManyToManyField(user_model, blank=True, related_name='user_likes')

    def __str__(self) -> str:
        result = self.message[:50]
        if len(self.message) > 49:
            result += '...'
        return result
    
    def save(self, *args, **kwargs):
        self.message_html = misaka.html(self.message)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('posts:single',
                       kwargs={
                           'slug': self.user.username,
                           'pk': self.pk})

    def like(self, user_profile):
        if user_profile.user not in self.likes.all():
            self.likes.add(user_profile.user)
            user_profile.likes.add(self)

    def unlike(self, user_profile):
        if user_profile.user in self.likes.all():
            self.likes.remove(user_profile.user)
            user_profile.likes.remove(self)

    @property
    def is_liked(self, user):
        return user in self.likes.all()
    
    @property
    def like_count(self):
        return self.likes.count()
 
    class Meta:
        ordering = ['-created_at']
        unique_together = ['user', 'message']

posts/forms.py
from django import forms
from . import models


class PostForm(forms.ModelForm):
    class Meta:
        fields = ("message", "post_pic")
        model = models.Post

    def __init__(self, *args, **kwargs):
        user = kwargs.pop("user", None)
        super().__init__(*args, **kwargs)
        # if user is not None:
        #     self.fields["group"].queryset = (
        #         models.Group.objects.filter(
        #             pk__in=user.groups.values_list("group__pk")
        #         )
        #     )

posts/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse
from django.http import Http404
from django.views import generic

from braces.views import SelectRelatedMixin

from . import models
from . import forms

from user_profile.models import UserProfile

# Create your views here.
user_model = get_user_model()

class PostList(LoginRequiredMixin, SelectRelatedMixin, generic.ListView):
    model = models.Post
    select_related = ('user', )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['liked_posts'] = UserProfile.objects.get(user__exact=self.request.user).likes.all()
        return context


class UserPosts(LoginRequiredMixin, generic.ListView):
    model = models.Post
    template_name = 'posts/user_post_list.html'
    
    def get_queryset(self):
        try:
            self.post_user = user_model.objects.prefetch_related('posts').get(
                username__iexact=self.kwargs.get('slug'))
        except user_model.DoesNotExist:
            raise Http404
        else:
            return self.post_user.posts.all()
        
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post_user'] = self.post_user
        context['liked_posts'] = UserProfile.objects.get(user__exact=self.request.user).likes.all()
        return context
    

class PostDetail(LoginRequiredMixin, SelectRelatedMixin, generic.DetailView):
    model = models.Post
    select_related = ('user', )

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(
            user__username__iexact=self.kwargs.get('slug'))
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['liked_posts'] = UserProfile.objects.get(user__exact=self.request.user).likes.all()
        return context


class CreatePost(LoginRequiredMixin, SelectRelatedMixin, generic.CreateView):
    # fields = ('message', 'picture')
    model = models.Post
    form_class = forms.PostForm

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        # # Check if they provided a profile picture
        # if 'profile_pic' in request.FILES:
        #     print('found it')
        #     # If yes, then grab it from the POST form reply
        #     profile.profile_pic = request.FILES['profile_pic']
        self.object.save()
        return super().form_valid(form)
    

class DeletePost(LoginRequiredMixin, SelectRelatedMixin,generic.DeleteView):
    model = models.Post
    select_related = ('user', )
    success_url = reverse_lazy('posts:all')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id = self.request.user.id)
    
    def delete(self, *args, **kwargs):
        messages.success(self.request, 'Post Deleted')
        return super().delete(*args, **kwargs)


class LikeView(LoginRequiredMixin, generic.RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        return self.request.POST.get('next', reverse('posts:all'))

    def get(self, request, *args, **kwargs):
        try:
            liking_user_profile = UserProfile.objects.get(user__exact=self.request.user)
            liked_post = models.Post.objects.get(pk__iexact=self.kwargs.get('pk'))

        except UserProfile.DoesNotExist:
            messages.warning(
                self.request,
                "Something went wrong..."
            )

        else:
            liked_post.like(liking_user_profile)
            messages.success(
                self.request,
                "You liked a post."
            )
        return super().get(request, *args, **kwargs)


class UnlikeView(LoginRequiredMixin, generic.RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        return self.request.POST.get('next', reverse('posts:all'))

    def get(self, request, *args, **kwargs):
        try:
            liking_user_profile = UserProfile.objects.get(user__exact=self.request.user)
            liked_post = models.Post.objects.get(pk__iexact=self.kwargs.get('pk'))

        except UserProfile.DoesNotExist:
            messages.warning(
                self.request,
                "Something went wrong..."
            )

        else:
            liked_post.unlike(liking_user_profile)
            messages.success(
                self.request,
                "You unliked a post."
            )
        return super().get(request, *args, **kwargs)
    
class UserLikesPostsList(LoginRequiredMixin, generic.ListView):
    model = models.Post
    template_name = 'posts/user_likes_post_list.html'
    
    def get_queryset(self):
        try:
            self.user_likes_post = UserProfile.objects.get(
                slug__iexact=self.kwargs.get('slug'))
        except user_model.DoesNotExist:
            raise Http404
        else:
            return self.user_likes_post.likes.all()
        
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user_likes_post'] = self.user_likes_post
        context['liked_posts'] = UserProfile.objects.get(user__exact=self.request.user).likes.all()
        return context

posts/templates/posts/_post.html
<div class="card w-75 m-5">
	<a href="{% url 'posts:single' slug=post.user.username pk=post.pk %}">
		<img src="{{ post.post_pic.url}}" class="card-img-top" alt="{{ post.message }}">
	</a>
	<div class="card-body">
	<h5 class="card-title"><a href="{% url 'posts:for_user' slug=post.user.username %}">@{{ post.user.username }}</a></h5>
		<p class="card-text">{{ post.message_html|safe }}</p>
		<div>
			<p>Likes: {{ post.like_count }}</p>
			<div class="">
				{% if user.is_authenticated and post.user == user and not hide_delete %}
				<div class="text-end">
					<a href="{% url 'posts:delete' pk=post.pk %}" title="delete" class="btn btn-danger">
						<span class="material-symbols-outlined">
							delete
						</span>
						<span class="icon-label">Delete</span>
					</a>
				</div>
				{% endif %}
				{% if user.is_authenticated and post.user != user %}
					{% if post in liked_posts %}
						<form method="POST" action="{% url 'posts:unlike' pk=post.pk %}">
							{% csrf_token %}
							<input type="hidden" name="next" value="{{ request.path }}">
							<button class="btn btn-outline-primary" type=submit>Unlike</button>
						</form>
					{% else %}
						<form method="POST" action="{% url 'posts:like' pk=post.pk %}">
							{% csrf_token %}
							<input type="hidden" name="next" value="{{ request.path }}">
							<button class="btn btn-primary" type=submit>Like</button>
						</form>
					{% endif %}
				{% endif %}
			</div>
		</div>
	</div>
</div>

posts/templates/posts/post_base.html
{% extends "base.html" %}

{% block content %}
	<div class="container">
    	{% block prepost %}{% endblock %}
		{% block post_content %}{% endblock %}
	</div>
{% endblock %}

posts/templates/posts/post_confirm_delete.html
{% extends "posts/post_base.html" %}

{% block post_content %}
<h3>Are you sure you want to delete this post?</h3>

<div class="posts">
	{% include "posts/_post.html" with post=object hide_delete=True %}
</div>

<form method="POST">
	{% csrf_token %}
	<input type="submit" value="Confirm Delete" class="btn btn-danger btn-large">
	<a href="{% url 'posts:single' slug=user.username pk=object.pk %}" class="btn btn-light btn-large">Cancel</a>
</form>

{% endblock %}

posts/templates/posts/post_detail.html
{% extends "posts/post_base.html" %}

{% block post_content %}
<!-- <div class="col-md-8"> -->
    {% include "posts/_post.html" %}
<!-- </div> -->
{% endblock %}

posts/templates/posts/post_form.html
{% extends "posts/post_base.html" %}

{% load bootstrap5 %}

{% block post_content %}
<h4>Create New Post</h4>
<form method="POST" action="{% url 'posts:create' %}" enctype="multipart/form-data" id="postForm">
	{% csrf_token %}
	{% bootstrap_form form %}
	{% buttons %}
		<button type="submit" class="btn btn-primary btn-large">Post</button>
	{% endbuttons %}
</form>
{% endblock %}

posts/templates/posts/post_list.html
{% extends "posts/post_base.html" %}
{% load humanize %}

{% block pre_post_content %}
<div class="col-md-4">

</div>
{% endblock %}
{% block post_content %}
<div class="row  justify-content-center">
	<div class="col-md-8">
		{% for post in post_list %}
			{% include "posts/_post.html" with hide_delete=True %}
		{% endfor %}
	</div>
	{% comment %} <div class="col-md-4">
		Userlist
	</div> {% endcomment %}
</div>
{% endblock %}

posts/templates/posts/user_likes_post_list.html
{% extends "posts/post_base.html" %}

{% block prepost %}
<div class="col-md-4">
	<h1 class="font-cursive">@{{ user_likes_post.slug }}'s likes</h1>
</div>
{% endblock %}

{% block post_content %}
<div class="row justify-content-center">
<div class="col-md-8">
	{% for post in post_list %}
		{% include "posts/_post.html" %}
    {% empty %}
        <p class="mt-4">Nothing here yet.</p>
	{% endfor %}
</div>
</div>
{% endblock %}

posts/templates/posts/user_post_list.html
{% extends "posts/post_base.html" %}

{% block prepost %}
<div class="col-md-4">
	<h1 class="font-cursive">@{{ post_user.username }}'s Posts</h1>
</div>
{% endblock %}

{% block post_content %}
<div class="row justify-content-center">
<div class="col-md-8">
	{% for post in post_list %}
		{% include "posts/_post.html" %}
	{% endfor %}
</div>
</div>
{% endblock %}